services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres-lab-6
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data_sixth_laboratory:/var/lib/postgresql/data
      - ./1.sql:/docker-entrypoint-initdb.d/01.sql
      - ./2.sql:/docker-entrypoint-initdb.d/02.sql
      - ./3.sql:/docker-entrypoint-initdb.d/03.sql
      - ./4.sql:/docker-entrypoint-initdb.d/04.sql
      - ./5.sql:/docker-entrypoint-initdb.d/05.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - sixth_laboratory

  pgadmin:
    image: dpage/pgadmin4:9.3.0
    container_name: pgadmin-lab-6
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sixth_laboratory

volumes:
  postgres_data_sixth_laboratory:

networks:
  sixth_laboratory:
    driver: bridge
