"""Generate bundled letter statistics for Vigenere cryptanalysis.

English source: Lewis Carroll, Alice's Adventures in Wonderland, Project Gutenberg
eBook #11, https://www.gutenberg.org/ebooks/11 (public domain in the USA).
Russian source: the repository's lab 4 corpus. The ru-yo model has sparse Ё data,
so all counts receive Laplace smoothing in Rust.

Run: python3 scripts/vigenere/generate_language_model.py
"""

from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[2]
ENGLISH_URL = "https://www.gutenberg.org/cache/epub/11/pg11.txt"
LATIN = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
RU_YO = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"
RU_NO_YO = "АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ_"


def indices(text, alphabet, fold_yo=False):
    positions = {char: i for i, char in enumerate(alphabet)}
    for char in text.upper():
        if fold_yo and char == "Ё":
            char = "Е"
        if char in positions:
            yield positions[char]


def counts(text, alphabet, fold_yo=False):
    symbols = list(indices(text, alphabet, fold_yo))
    n = len(alphabet)
    letters = [0] * n
    pairs = [0] * (n * n)
    for symbol in symbols:
        letters[symbol] += 1
    for first, second in zip(symbols, symbols[1:]):
        pairs[first * n + second] += 1
    return letters, pairs


def rust_array(name, values, width=16):
    lines = [f"pub const {name}: [u32; {len(values)}] = ["]
    for offset in range(0, len(values), width):
        lines.append("    " + ", ".join(map(str, values[offset:offset + width])) + ",")
    lines.append("];")
    return "\n".join(lines)


def main():
    with urlopen(ENGLISH_URL) as source:
        english = source.read().decode("utf-8-sig")
    english = english.split("*** START OF THE PROJECT GUTENBERG EBOOK", 1)[-1]
    english = english.split("*** END OF THE PROJECT GUTENBERG EBOOK", 1)[0]
    russian = (ROOT / "artifacts/lab_04_vigenere/corpus_ru.txt").read_text()
    sections = [
        "//! Bundled language counts for ciphertext-only attacks.\n",
        "//! Generated by scripts/vigenere/generate_language_model.py.\n",
        "//! English: Project Gutenberg eBook #11; Russian: the repository's lab 4 corpus.\n\n",
    ]
    for name, text, alphabet, fold_yo in [
        ("EN", english, LATIN, False),
        ("RU_YO", russian, RU_YO, False),
        ("RU_NO_YO", russian, RU_NO_YO, True),
    ]:
        letters, pairs = counts(text, alphabet, fold_yo)
        sections.append(rust_array(f"{name}_LETTERS", letters) + "\n\n")
        sections.append(rust_array(f"{name}_BIGRAMS", pairs) + "\n\n")
    destination = ROOT / "crates/vigenere/src/domain/language_counts.rs"
    destination.write_text("".join(sections))


if __name__ == "__main__":
    main()
