global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "image-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["image-service-app-backend:8001"]
  - job_name: "user-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user-service-app-backend:8000"]
  