[project]
name = "5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref==3.7.2",
    "asttokens==2.2.1",
    "async-timeout==4.0.3",
    "backcall==0.2.0",
    "certifi==2023.7.22",
    "cffi==1.15.1",
    "charset-normalizer==3.2.0",
    "colorama==0.4.6",
    "cryptography==41.0.3",
    "decorator==5.1.1",
    "defusedxml==0.7.1",
    "django==4.2.1",
    "django-debug-toolbar==4.2.0",
    "django-extensions==3.2.3",
    "django-ranged-response==0.2.0",
    "django-simple-captcha==0.5.18",
    "executing==1.2.0",
    "gunicorn>=23.0.0",
    "hiredis==2.2.3",
    "idna==3.4",
    "ipython==8.14.0",
    "jedi==0.19.0",
    "markupsafe==2.1.3",
    "matplotlib-inline==0.1.6",
    "oauthlib==3.2.2",
    "parso==0.8.3",
    "pickleshare==0.7.5",
    "pillow==10.0.0",
    "prompt-toolkit==3.0.39",
    "psycopg2==2.9.7",
    "psycopg2-binary>=2.9.10",
    "pure-eval==0.2.2",
    "pycparser==2.21",
    "pygments==2.16.1",
    "pyjwt==2.8.0",
    "pyopenssl==23.2.0",
    "python-dotenv>=1.1.0",
    "python3-openid==3.2.0",
    "redis==5.0.0",
    "requests==2.31.0",
    "requests-oauthlib==1.3.1",
    "six==1.16.0",
    "social-auth-app-django==5.3.0",
    "social-auth-core==4.4.2",
    "sqlparse==0.4.4",
    "stack-data==0.6.2",
    "traitlets==5.9.0",
    "typing-extensions==4.7.1",
    "tzdata==2023.3",
    "urllib3==2.0.4",
    "wcwidth==0.2.6",
    "werkzeug==2.3.7",
]
