-- INSERT INTO "STUDENT1" 

SELECT "STUDENT"."STUDENT_ID", "STUDENT"."SURNAME", "STUDENT"."NAME", "STUDENT"."STIPEND", "STUDENT"."KURS", "STUDENT"."CITY", "STUDENT"."BIRTHDAY", "STUDENT"."UNIV_ID"
FROM "STUDENT"
WHERE "STUDENT"."STUDENT_ID" in (

	SELECT "STUDENT_ID"
	FROM "EXAM_MARKS"
	WHERE "MARK" >=3
	GROUP BY "STUDENT_ID"
	HAVING COUNT("MARK") > 1);
	
SELECT *
FROM "STUDENT";