sonar.projectKey=lab_04_nist
sonar.projectName=Лабораторная № 4 — NIST-тест
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/target/**
sonar.sourceEncoding=UTF-8

sonar.language=rust
sonar.community.rust.clippy.reportPaths=clippy.json

# Принудительно включить .rs-файлы в text-анализ (CE без community-rust)
sonar.text.inclusions=**/*.rs
sonar.inclusions=**/*.rs
