services:
  postgres-lab-3-question-5:
    image: postgres:16.3-alpine
    container_name: postgres-lab-3-question-5
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data_third_laboratory_question_5:/var/lib/postgresql/data
      - ./scripts/initdb/01_init_schemas.sql:/docker-entrypoint-initdb.d/01_init_schemas.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - third_laboratory_question_fifth

  postgres-lab-3-question-5-restore:
    image: postgres:16.3-alpine
    container_name: postgres-lab-3-question-5-restore
    depends_on:
      postgres-lab-3-question-5:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./scripts/restore/script.sh:/script.sh
      - ./scripts/restore/istudents_lab.backup:/dump/istudents_lab.backup
    command: ["sh", "-c", "chmod +x /script.sh && ./script.sh"]
    networks:
      - third_laboratory_question_fifth

  postgres-lab-3-question-5-apply-indexes:
    image: postgres:16.3-alpine
    container_name: postgres-lab-3-question-5-apply-indexes
    depends_on:
      postgres-lab-3-question-5-restore:
        condition: service_completed_successfully
    env_file:
      - .env
    command: ["sh", "-c", "chmod +x /script.sh && ./script.sh"]
    volumes:
      - ./scripts/indexes/03_init_indexes.sql:/scripts/03_init_indexes.sql
      - ./scripts/indexes/script.sh:/script.sh
    networks:
      - third_laboratory_question_fifth

  pgadmin-lab-3-question-5:
    image: dpage/pgadmin4:9.3.0
    container_name: pgadmin-lab-3-question-5
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      postgres-lab-3-question-5:
        condition: service_healthy
    networks:
      - third_laboratory_question_fifth

volumes:
  postgres_data_third_laboratory_question_5:

networks:
  third_laboratory_question_fifth:
    driver: bridge
