# Generated by Django 2.2.28 on 2022-11-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_3_0_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='masterpass_check',
            field=models.CharField(default='', max_length=256),
        ),
    ]
