# Generated by Django 2.2.28 on 2023-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='binary_path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
