# Generated by Django 3.2.18 on 2023-05-15 07:30

from django.db import migrations, models

def set_default_connection_params(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Connection = apps.get_model("app", "Connection")

    default_params = {
        "postgresql": {"sslmode": "prefer"},
        "mysql": {"ssl": {"ssl": True}},
        "mariadb": {"ssl": {"ssl": True}},
        "oracle": {"protocol": "tcps"}
    }

    for conn in Connection.objects.all():
        conn.connection_params = default_params.get(conn.technology.name, {})
        conn.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userdetails_binary_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connection_params',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(set_default_connection_params, migrations.RunPython.noop)
    ]
