# Generated by Django 3.2.18 on 2023-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_connection_connection_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_format',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
