# Generated by Django 3.2.18 on 2023-05-26 14:38

from django.db import migrations, models

def update_tab_database_values(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Tab = apps.get_model("app", "Tab")

    for tab in Tab.objects.all():
        if tab.database is None:
            tab.database = tab.connection.database
            tab.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userdetails_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='database',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RunPython(update_tab_database_values, migrations.RunPython.noop)
    ]
