# Generated by Django 3.2.18 on 2023-06-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tab_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='last_used_database',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
