# Generated by Django 3.2.18 on 2023-10-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userdetails_pigz_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='autocomplete',
            field=models.BooleanField(default=True),
        ),
    ]
