# Generated by Django 3.2.18 on 2023-12-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_connection_last_access_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='autocomplete',
        ),
        migrations.AddField(
            model_name='connection',
            name='autocomplete',
            field=models.BooleanField(default=True),
        ),
    ]
