# Generated by Django 3.2.18 on 2024-01-29 08:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20231222_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonUnits',
            new_name='MonWidgets',
        ),
        migrations.RenameModel(
            old_name='MonUnitsConnections',
            new_name='MonWidgetsConnections',
        ),
    ]
