# Generated by Django 3.2.18 on 2024-01-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_monunits_and_monunitsconnections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monwidgets',
            name='is_default',
        ),
        migrations.AddField(
            model_name='monwidgets',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
