# Generated by Django 3.2.18 on 2024-02-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_query_and_console_history_database'),
        ('app', '0016_replace_is_default_with_editable'),
    ]

    operations = [
    ]
