# Generated by Django 3.2.18 on 2024-02-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_userdetails_restore_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='scroll_tree',
            field=models.BooleanField(default=True),
        ),
    ]
