# Generated by Django 4.2.11 on 2024-06-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userdetails_scroll_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='color_label',
            field=models.IntegerField(default=0),
        ),
    ]
