# Generated by Django 4.2.16 on 2024-09-23 07:40

import uuid

from django.db import migrations, models


def update_group_names(apps, schema_editor):
    Group = apps.get_model("app", "Group")
    duplicate_group_names = (
        Group.objects.values("name")
        .annotate(models.Count("id"))
        .filter(id__count__gt=1)
    )
    duplicate_groups = Group.objects.filter(
        name__in=[item["name"] for item in duplicate_group_names]
    )

    for group in duplicate_groups:
        unique_group_name = f"{group.name}-{uuid.uuid4()}"
        group.name = unique_group_name
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_connection_color_label"),
    ]

    operations = [
        migrations.RunPython(update_group_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_group_name"
            ),
        ),
    ]
