# Generated by Django 4.2.16 on 2024-10-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_userdetails_csv_delimiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='welcome_closed',
        ),
    ]
