# Generated by Django 3.2.18 on 2023-05-26 14:38

from django.db import migrations, models

def delete_old_settings(apps, schema_editor):
    MonWidgetsConnections = apps.get_model("app", "MonWidgetsConnections")
    MonWidgetsConnections.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_userdetails_welcome_closed'),
    ]

    operations = [
        migrations.RunPython(delete_old_settings, migrations.RunPython.noop)
    ]
