# Generated by Django 4.2.16 on 2025-03-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_drop_old_dashboard_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='monwidgetsconnections',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monwidgetsconnections',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
