services:
  zombie:
    image: alpine:3.22.1
    container_name: zombie
    command: >
      sh -c "
      apk add --no-cache iptables drill;
      iptables -A INPUT -p tcp --tcp-flags ALL SYN,ACK -j REJECT --reject-with tcp-reset;
      # Генерируем фоновый трафик
      while true; do
        drill @8.8.8.8 example.com >/dev/null 2>&1;
        sleep 0.5;
      done &
      # Бесконечное ожидание
      tail -f /dev/null
      "
    cap_add:
      - NET_ADMIN
    networks:
      sixth_laboratory_network:
        ipv4_address: 192.168.6.11

  target:
    image: nginx:alpine
    container_name: target
    networks:
      sixth_laboratory_network:
        ipv4_address: 192.168.6.22

  attacker:
    image: instrumentisto/nmap:latest  # Используем образ с предустановленным nmap
    container_name: attacker
    command: ["tail", "-f", "/dev/null"]
    cap_add:
      - NET_ADMIN
    networks:
      sixth_laboratory_network:
        ipv4_address: 192.168.6.33

networks:
  sixth_laboratory_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.6.0/24