"""init

Revision ID: 7023bee3c029
Revises: 
Create Date: 2025-03-06 19:02:44.059360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.infrastructure.adapters.alchemy.type_decorators import PhoneNumberTypeDecorator, EmailTypeDecorator, \
    PasswordTypeDecorator, RoleDecorator, StatusDecorator, URLTypeDecorator, GenderTypeDecorator

# revision identifiers, used by Alembic.
revision: str = '7023bee3c029'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('email', EmailTypeDecorator(length=100), nullable=False),
    sa.Column('password', PasswordTypeDecorator(length=50), nullable=False),
    sa.Column('role', RoleDecorator(length=15), nullable=False),
    sa.Column('status', StatusDecorator(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', PhoneNumberTypeDecorator(length=16), nullable=True),
    sa.Column('photo', URLTypeDecorator(length=255), nullable=True),
    sa.Column('gender', GenderTypeDecorator(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bio_id', sa.UUID(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bio_id'], ['bios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_networks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bio_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bio_id'], ['bios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_networks')
    op.drop_table('addresses')
    op.drop_table('bios')
    op.drop_table('users')
    op.drop_table('platforms')
    # ### end Alembic commands ###
