[project]
name = "8"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncpg>=0.30.0",
    "matplotlib>=3.10.3",
    "pandas>=2.2.3",
    "pydantic-settings>=2.9.1",
    "sqlalchemy>=2.0.41",
]
