services:
  telegram-service-app:
    restart: unless-stopped
    container_name: telegram-service-app
    image: telegram-service-app
    build:
      context: ..
      dockerfile: Dockerfile
    command: "gunicorn --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4 --timeout 120 --log-level info app.main:create_app"
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    depends_on:
      postgres-app-telegram:
        condition: service_healthy
    networks:
      - telegram-service

  postgres-app-telegram:
    container_name: postgres-app-telegram
    image: postgres:16.3-alpine
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres-app-telegram-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${DATABASE_USER} -d $${DATABASE_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - telegram-service
    env_file:
      - ../.env

volumes:
 postgres-app-telegram-volume:

networks:
  telegram-service:
    driver: bridge