services:
  postgres:
    image: postgres-with-audit:local-6
    container_name: postgres-lab-10-var-6
    build: ./
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data_tenth_laboratory_var_6:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - tenth_laboratory_var_6
    command: postgres -c config_file=/etc/postgresql.conf

  pgadmin:
    image: dpage/pgadmin4:9.3.0
    container_name: pgadmin-lab-10-var-6
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tenth_laboratory_var_6

volumes:
  postgres_data_tenth_laboratory_var_6:

networks:
  tenth_laboratory_var_6:
    driver: bridge
