services:
  second-laboratory-database:
    image: mysql:9.0.0
    container_name: second-laboratory-database
    volumes:
      - mysql_data_2nd_laboratory_correct:/var/lib/mysql
      - ./resources/certs:/etc/mysql/certs
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: [
      "mysqld",
      "--ssl-ca=/etc/mysql/certs/ca.pem",
      "--ssl-cert=/etc/mysql/certs/server-cert.pem",
      "--ssl-key=/etc/mysql/certs/server-key.pem",
      "--bind-address=0.0.0.0",
      "--require_secure_transport=ON",
      "--secure_file_priv=NULL"
    ]
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env
    restart: "unless-stopped"
    networks:
      - second-laboratory
    healthcheck:
      test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10

volumes:
  mysql_data_2nd_laboratory_correct:

networks:
  second-laboratory:
    driver: bridge