FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
        dnsutils \
        iproute2 \
        iputils-ping \
        ca-certificates \
        curl \
        procps \
    && rm -rf /var/lib/apt/lists/*

CMD ["sleep", "infinity"]
